-- Works with apache derby :>

create database bank;
use bank;

show tables;
CREATE TABLE Users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_ssn_id VARCHAR(20),
    emp_id VARCHAR(20),
    role VARCHAR(20) CHECK (role IN ('Customer', 'Employee', 'Admin')),
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE UserProfiles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT UNIQUE,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    phone_no VARCHAR(15),
    address TEXT,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE LoanRequests (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    performed_by_id INT NULL,
    loan_amount DECIMAL(10, 2) NOT NULL,
    loan_type VARCHAR(20) CHECK (loan_type IN ('Personal', 'Mortgage', 'Auto')) NOT NULL,
    status VARCHAR(20) CHECK (status IN ('Pending', 'Approved', 'Rejected')) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    CONSTRAINT loan_request_fk_user FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE,
    CONSTRAINT loan_request_fk_performed_by FOREIGN KEY (performed_by_id) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE Accounts (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT UNIQUE,
    balance DECIMAL(15, 2) DEFAULT 1000,
    account_type VARCHAR(20) CHECK (account_type IN ('Savings', 'Checking')) NOT NULL,
    status VARCHAR(20) CHECK (status IN ('Active', 'Inactive', 'Closed')) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE Transactions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INT NOT NULL,
    performed_by_id INT NOT NULL,
    transaction_type VARCHAR(20) CHECK (transaction_type IN ('Deposit', 'Withdraw', 'Transfer')) NOT NULL,
    amount DECIMAL(15, 2) NOT NULL,
    status VARCHAR(20) CHECK (status IN ('Pending', 'Completed', 'Failed')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(account_id) REFERENCES Accounts(id) ON DELETE CASCADE,
    FOREIGN KEY(performed_by_id) REFERENCES Users(id) ON DELETE CASCADE
);


-- Registering customer or employee in the system
insert into Users (role, email, password)
values('Customer', 'ukcustomer@tcs.com', 'abc@1234');

 -- Account creating for the customer
insert into Accounts(user_id, balance, account_type, status)
values (last_insert_id(), 0.00, 'Savings', 'Active');

-- creating user profile for the same user
insert into UserProfiles (user_id, first_name, last_name, phone_no, address)
values (last_insert_id(), 'John', 'Doe', '1234' ,'123 Main street');

-- Fetching the User profile using users pk 
SELECT u.id AS user_id, u.emp_id, u.role, u.email, u.password, u.created_at, u.updated_at,
       up.first_name, up.last_name, up.phone_no, up.address
FROM Users u
JOIN UserProfiles up ON u.id = up.user_id
WHERE u.id = 1;




-- customer initiating the loan request 
insert into LoanRequests(user_id, loan_amount,loan_type, status)
values(last_insert_id(), 5000.00, 'Personal', 'Pending');



-- employee initiating the loan request 
insert into loanrequests (user_id, performed_by_id, loan_amount, loan_type, status)
values (
(select id from users where customer_ssn_id = 'c100'),
(select id from users where emp_id = 'e100'),
1000.00,
'Auto',
'Pending');

-- customer creating transaction
insert into Transactions (user_id, transaction_type, amount, status)
values (last_insert_id(), 'Deposit', '1000.00', 'Completed');

-- employee initiating the transaction for a customer
insert into transaction (account_id, performed_by_id, transaction_type, amount, status)
values (
	(select id from Accounts where user_id= (select id from Users where  customer_ssn_id="C100")),
    (select id from users where emp_id = 'E100'),
    'Deposit',
    2000.00,
    'Completed'
);


-- listing all transactions
select * from transactions;

-- listing all transaction created by particuclar emp
select t.*
from transactions t
join users u on t.performed_by_id = u.id
where u.emp_id = 'E100';
 


use bank;
show tables;

drop table Users;
drop table UserProfiles;
drop table Accounts;
drop table transactions;
drop table loanrequests;



